apiVersion: v1
kind: Service
metadata:
  name: eminsights-frontend
spec:
  type: NodePort
  selector:
    app: eminsights-frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30008
